spring:
  application:
    name: service-discovery

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false  # 실제 운영 시에는 true로 설정
    eviction-interval-timer-in-ms: 3000

  client:
    register-with-eureka: false
    fetch-registry: false