server:
  port: 8000

spring:
  application:
    name: gateway-service

  config:
    import: classpath:/bootstrap.yaml

  cloud:
    gateway:
      routes:
        # Login-Service
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/oauth2/authorization/**
            - Method=GET
          filters:
            - BeforeLoginFilter

        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**
            - Method=GET

        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/logout
            - Method=POST
          filters:
            - AuthorizationCookieFilter

        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/img/**
            - Method=GET

        # User-Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/check
            - Method=POST

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - AuthorizationCookieFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users, /users/**
            - Method=GET
          filters:
            - AuthorizationCookieFilter

        # Store-Service
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/categories, /images/**
            - Method=GET

        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/stores, /stores/**
            - Method=GET
          filters:
            - AuthorizationCookieFilter

logging:
  level:
    com.megamaker.gatewayservice: debug

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh, busrefresh