server:
  port: 8000

spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      name: delibird
      enabled: true

    gateway:
      routes:
        # Login-Service
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login, /oauth2/**
            - Method=GET
          filters:
            - BeforeLoginFilter

        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/logout
            - Method=POST
          filters:
            - AuthorizationCookieFilter

        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/img/**
            - Method=GET

        # User-Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - AuthorizationCookieFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/
            - Method=GET
          filters:
            - AuthorizationCookieFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/check
            - Method=POST

#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/actuator/**
#            - Method=GET, POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
            - Method=GET

logging:
  level:
    com.megamaker.gatewayservice: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh