server:
  port: 8000
#  ssl:
#    enabled: true
#    key-alias: tomcat
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12

spring:
  application:
    name: gateway-service

  config:
    import:
      - classpath:/bootstrap.yaml
#      - classpath:/secret.yaml

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"  # 개발용
              - "https://delibird.store"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            exposedHeaders: # 노출할 응답 헤더 추가
              - Auth
        add-to-simple-url-handler-mapping: true

      routes:
        # Login-Service
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/oauth2/authorization/**
            - Method=GET
          filters:
            - BeforeLoginFilter

        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**, /img/**
            - Method=GET

        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/logout
            - Method=POST
          filters:
            - AuthorizationCookieFilter

        # User-Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/check
            - Method=POST

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - AuthorizationCookieFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users, /users/**
            - Method=GET
          filters:
            - AuthorizationCookieFilter

        # Store-Service
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/categories, /products, /images/**
            - Method=GET

        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/stores, /stores/**
            - Method=GET
          filters:
            - AuthorizationCookieFilter

        # Cart-Service
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart
            - Method=POST

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart
            - Method=GET

        # Order-Service
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders
            - Method=POST
          filters:
            - AuthorizationCookieFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders, /reviews/**
            - Method=GET
          filters:
            - AuthorizationCookieFilter

logging:
  level:
    com.megamaker.gatewayservice: debug
    org.springframework.web.cors.reactive.CorsWebFilter: debug
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh, busrefresh