spring:
  application:
    name: user-service

server:
  port: 0


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}
    lease-renewal-interval-in-seconds: 1  # ?? ??? ?? ??
    lease-expiration-duration-in-seconds: 2  # ?? ??? ?? ??
