server:
  port: 0

spring:
  application:
    name: user-service

  config:
    import: classpath:/bootstrap.yaml


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.megamaker.userservice: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh