server:
  port: 0

spring:
  application:
    name: product-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      name:
        - delibird
        - product-service