server:
  port: 0

spring:
  application:
    name: cart-service

  config:
    import: classpath:/bootstrap.yaml

logging:
  level:
    com.megamaker.cartservice: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh