spring:
  application:
    name: login-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      name: delibird, login-service

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

#oauth2:
#  logout:
#    uri:
#      naver: https://nid.naver.com/oauth2.0/token