server:
  port: 8080

spring:
  application:
    name: login-service

  config:
    import: classpath:/bootstrap.yaml

  cloud:
    bus:
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

#oauth2:
#  logout:
#    uri:

#      naver: https://nid.naver.com/oauth2.0/token