server:
  port: 8888

spring:
  application:
    name: config-service

  config:
    import: classpath:secret.yaml

  kafka:
    bootstrap-servers: http://api.delibird.store:9092

  cloud:
    bus:  # 카프카 토픽명
      destination: delibird-config

    config:
      server:
        git:
          uri: https://github.com/ness727/delibird-config
          basedir: ./config-git  # 임시 디렉토리 대신 임의의 폴더로 받기
          
management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh