server:
  port: 0

spring:
  application:
    name: store-service

  config:
    import: classpath:/bootstrap.yaml

  data:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.megamaker.storeservice: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh