server:
  port: 0

spring:
  application:
    name: store-service

  data:
    web:
      pageable:
        one-indexed-parameters: true

  config:
    import:
      - optional:configserver:http://localhost:8888

  cloud:
    config:
      name: delibird, database

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.megamaker.storeservice: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh